### ISSUE TITLE
Polling questions - Input via Arduino/Joystick

### ISSUE THREAD

**Issue by dougshell** [geefr/stepmania-linux-goodies#1]
I am currently running Stepmania compiled from source but an curious if your work here can help ensure I have 1ms polling.

Any help would be great

**Comment by geefr** [comment]
Oh dear someone actually asked for more help :P

I guess make sure you have a read of this: https://github.com/geefr/stepmania-linux-goodies/wiki/So-You-Think-You-Have-Polling-Issues

Then if you're using a keyboard/ipac make sure you've got the latest from 5_1-new branch. 
After that it's time to worry about actual polling rates/etc.

If you're using some other input that isn't a keyboard (piuio, any normal joystick etc) then let me know and I'll see if there's any know issues etc

**Comment by dougshell** [comment]
I am using an Arduino control box. It uses joystick code and identifies and
a game device.

I have installed low latency kernel

**Comment by geefr** [comment]
A low latency kernel won't make much difference if the polling rate is set too low

Assuming you're using a modern kernel you need to add jspoll=1 to the arguments: https://askubuntu.com/questions/19486/how-do-i-add-a-kernel-boot-parameter

And then you should have the fastest polling rate possible on the software side.

Whether or not the arduino can support 1000hz, or whether the code running on the arduino can run fast enough is another question, and not really one I can answer.

The evhz executable can be used to check polling rates, but last I checked you need to edit the source code first as it's only detects mice by default: https://gitlab.com/iankelling/evhz

**Comment by dougshell** [comment]
so simply added jspoll=1 to the boot parameter?

**Comment by geefr** [comment]
Find the line that has this:
            if(event.type == EV_REL || event.type == EV_ABS) {

And change it to this:
            if( 1 )

Then ./run in order to build/run, evhz should now respond to the keyboard/everything else.
Mash the input as fast as possible/jump on the pad lots. If you're lucky and manage to hit 2 buttons within 1 ms you'll end up with some output like this (It'll only list as fast as you can press, so you'll need to get lucky to actually see 1000hz listed :P ):

AT Translated Set 2 keyboard: Latest   333Hz, Average   227Hz
AT Translated Set 2 keyboard: Latest   142Hz, Average   228Hz
AT Translated Set 2 keyboard: Latest   250Hz, Average   231Hz
AT Translated Set 2 keyboard: Latest  1000Hz, Average   247Hz
AT Translated Set 2 keyboard: Latest   200Hz, Average   244Hz

**Comment by dougshell** [comment]
I will look into this when I return home. Which file specifically.

Also, I will simply try to code a loop into my Arduino code to simulate
switching input back and forth between two buttons

Then I wont need to get lucky.

Thank you for your assistance

**Comment by geefr** [comment]
There is only one file in evhz, so in evhz.c ;)
I'm using the latest from https://gitlab.com/iankelling/evhz

**Comment by dougshell** [comment]
Sorry for not getting back to you.

I have a few files in my evhz which is why i was confused. However, i found the line in evhz.c and made the changes.

I am happy to report

Arduino LLC Arduino Micro: Latest    21Hz, Average   104Hz
Arduino LLC Arduino Micro: Latest  1000Hz, Average   119Hz

Thank you. Consider this issue solved and closed
